"""
This module defines the URL patterns for the accounts app.
It uses a router to handle the ViewSet for follow/unfollow actions.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserRegistrationView, UserLoginView, UserFollowViewSet

# Create a router to automatically generate URLs for the UserFollowViewSet
router = DefaultRouter()
router.register(r'users', UserFollowViewSet, basename='users')

urlpatterns = [
    # URL for user registration.
    path('register/', UserRegistrationView.as_view(), name='user-register'),
    # URL for user login.
    path('login/', UserLoginView.as_view(), name='user-login'),
    # Include the URLs generated by the router for the UserFollowViewSet
    path('', include(router.urls)),
]
