"""
This module defines the URL patterns for the posts app.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet, UserFeedView

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
    # URL for accessing the user's aggregated feed
    path('feed/', UserFeedView.as_view(), name='user-feed'),
]